# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 8a34d3c958c710c33997648d002a5aec39626e867af0e87bcccf8ede1d43af02379c7f93a311448a3bd6f728c3678de180b01b58b56a6de4941b4dbaf566eac4
  recaptcha_site_key: "6Lce02oUAAAAANDpuHPSPW1e6a0PJEPZF1JaCGGN"
  recaptcha_secret_key: "6Lce02oUAAAAAEsgHLDhl-TD3JThX-hUAeGG1P5O"
test:
  secret_key_base: 2a05c11635a122fe60cc7ec5fb39af3d4a7ab297ff5ba60f2f90461c7e13b24e55e78789433726aca277d916bfdba10cd26b120bd70ca18b27f1da829cc8653a

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
